---
AWSTemplateFormatVersion: '2010-09-09'
Resources:

#| Resource                          | Type                    | Description                                      |
#|------------------------------     |-------------------------|--------------------------------------------------|
#| GetSecretValueLambdaPolicy        | AWS::IAM::ManagedPolicy | IAM policy with GetSecretValue value permissions |
#| CostAnomalyAlertsLambdaRole      | AWS::IAM::Role          | IAM Role associated with the Lambda Functions    |
#| DescribeAccountNameLambdaPolicy   | AWS::IAM::ManagedPolicy | IAM policy to DescribeAccount Name               |
#| ReadAppConfigLambdaPolicy         | AWS::IAM::ManagedPolicy | A Policy to read AppConfig configurations        |
 
  ReadAppConfigLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - appconfig:GetConfiguration
          Resource: "*"
      Roles:
      - Ref: CostAnomalyAlertsLambdaRole  
  DescribeAccountNameLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: displayAccountNameEnabled
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - organizations:DescribeAccount
          Resource: "arn:aws:organizations::*:account/o-*/*"
      Roles:
      - Ref: CostAnomalyAlertsLambdaRole     
  CostAnomalyAlertsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
      Tags:
      - Key: Project
        Value: CostAnomalyAlerts


#| Resource                  | Type                  | Description                                                                     |
#|---------------------------|-----------------------|---------------------------------------------------------------------------------|
#| SnsTopicCostAnomaly       | AWS::SNS::Topic       | SNS Topic that shall receive notifications from Cost Explorer Anomaly Detection |
#| SnsTopicPolicyCostAnomaly | AWS::SNS::TopicPolicy | SNS Topic Access Policy                                                         |

  SnsTopicCostAnomaly:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !Ref CostAnomalyAlertsLambdaAliasProd
        Protocol: lambda
      Tags:
      - Key: Project
        Value: CostAnomalyAlerts
    DependsOn:
    - CostAnomalyAlertsLambda
  SnsTopicPolicyCostAnomaly:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument: 
        {
          "Statement": [
            {
            "Sid": "costalerts to publish",
            "Effect": "Allow",
            "Principal": { 
              "Service": "costalerts.amazonaws.com" 
              },
              "Action": "sns:Publish",
              "Resource": !Ref SnsTopicCostAnomaly
            },
            {
              "Sid": "Lambda to subscribe",
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"

              },
              "Action": [
                "sns:Subscribe",
                "sns:Receive"
                ],
              "Resource": !Ref SnsTopicCostAnomaly,
              "Condition": {
                "StringEquals": {
                  "lambda:FunctionArn": !Ref CostAnomalyAlertsLambdaAliasProd
                }

              }
            }
            ]
        }
          
      Topics: 
      - !Ref SnsTopicCostAnomaly

#| Resource                              | Type                    | Description                                            |
#|---------------------------------------|-------------------------|--------------------------------------------------------|
#| CostAnomalyAlertsLambda              | AWS::Lambda::Function   | Main Lambda Function that will call Slack Webhooks API |
#| CostAnomalyAlertsLambdaSnsPermission | AWS::Lambda::Permission | Permission for SNS to invoke CostAnomalyAlertsLambda  |
#| CostAnomalyAlertsLambdaVersion       | AWS::Lambda::Version    | A new Lambda Version. For a new version to be deployed, the logical resource name must be changed. |
#| CostAnomalyAlertsLambdaAliasProd     | AWS::Lambda::Alias      | An alias to route traffic to route to one of the Lambda versions.                                  |

  CostAnomalyAlertsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: s3Bucket
        S3Key: !Ref codePackage
      Description: Lambda Function to Send Cost Anomaly Alerts to different channels
      Handler: lambda_function.lambda_handler
      Role:
        Fn::GetAtt:
        - CostAnomalyAlertsLambdaRole
        - Arn
      Runtime: python3.7
      Layers: 
      - !FindInMap [AppConfigLayerArn, !Ref "AWS::Region", AppConfigLayerArn]
      Timeout: 15
      Tags:
      - Key: Project
        Value: CostAnomalyAlerts
  CostAnomalyAlertsLambdaVersion:
    Type: AWS::Lambda::Version
    DeletionPolicy: Retain
    Properties: 
      FunctionName: !GetAtt CostAnomalyAlertsLambda.Arn
  CostAnomalyAlertsLambdaAliasProd:
    Type: AWS::Lambda::Alias
    Properties: 
      FunctionName: !GetAtt CostAnomalyAlertsLambda.Arn
      FunctionVersion: !GetAtt CostAnomalyAlertsLambdaVersion.Version
      Name: prod
  CostAnomalyAlertsLambdaSnsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn:
        Ref: SnsTopicCostAnomaly
      FunctionName: !Ref CostAnomalyAlertsLambdaAliasProd

#| Resource              | Type                        | Description                            |
#|-----------------------|-----------------------------|----------------------------------------|
#| CostAnomalyAlertsApplication | AWS::AppConfig::Application | App Config Application.  |
  
  CostAnomalyAlertsApplication:
    Type: AWS::AppConfig::Application
    Properties: 
      Description: Cost Anomaly Alerts AppConfig Application
      Name: cost-anomaly-alerts-application
      Tags: 
      - Key: Project
        Value: CostAnomalyAlerts
  CostAnomalyAlertsgEnvironment:
    Type: AWS::AppConfig::Environment
    Properties: 
      ApplicationId: !Ref CostAnomalyAlertsApplication
      Name: cost-anomaly-alerts-environment
      Description: Cost Anomaly to Alerts AppConfig Application Environment
      Tags: 
      - Key: Project
        Value: CostAnomalyAlerts
  CostAnomalyAlertsConfigProfile:
    Type: AWS::AppConfig::ConfigurationProfile
    Properties: 
      ApplicationId: !Ref CostAnomalyAlertsApplication
      Name: cost-anomaly-alerts-configuration-profile
      Description: Cost Anomaly Alerts AppConfig Application Environment
      LocationUri: hosted
      Tags: 
      - Key: Project
        Value: CostAnomalyAlerts       
  CostAnomalyAlertsConfigVersion:
    Type: AWS::AppConfig::HostedConfigurationVersion
    Properties:
      ApplicationId: !Ref CostAnomalyAlertsApplication
      ConfigurationProfileId: !Ref CostAnomalyAlertsConfigProfile
      Content: !Sub
      - '{"feature-flags":{"displayAccountName":${displayAccountNameValueBoolean}},"routing-configurations":[{"default":true,"target-channels":[{"type":"MS_Teams","URL":"${teamsUrlString}"},{"type":"Slack","URL":"${slackUrlString}"}]}]}'
      - displayAccountNameValueBoolean: !Ref FeatureFlagDisplayAccountName
        teamsUrlString: !Ref defaultTeamsWebhookURL
        slackUrlString: !Ref defaultSlackWebhookURL
      ContentType: 'application/json'
  CostAnomalyAlertsDeploymemtStrategy:    
    Type: AWS::AppConfig::DeploymentStrategy
    Properties: 
      Name: cost-anomaly-alerts-deployment-strategy
      Description: Cost Anomaly Alerts Deployment Strategy
      DeploymentDurationInMinutes: 1
      FinalBakeTimeInMinutes: 1
      GrowthFactor: 100
      GrowthType: LINEAR
      ReplicateTo: NONE
      Tags: 
      - Key: Project
        Value: CostAnomalyAlerts 
  CostAnomalyAlertsDeploymemt:      
    Type: AWS::AppConfig::Deployment
    Properties: 
      ApplicationId: !Ref CostAnomalyAlertsApplication
      ConfigurationProfileId: !Ref CostAnomalyAlertsConfigProfile
      ConfigurationVersion: !Ref CostAnomalyAlertsConfigVersion
      DeploymentStrategyId: !Ref CostAnomalyAlertsDeploymemtStrategy
      Description: Cost Anomaly Alerts Deployment
      EnvironmentId: !Ref CostAnomalyAlertsgEnvironment
      Tags: 
      - Key: Project
        Value: CostAnomalyAlerts
    
#| Parameter       | Type   | Description                                                                                               |
#|-----------------|--------|-----------------------------------------------------------------------------------------------------------|
#| s3Bucket        | String | S3 bucket where the Lambda code package is stored                                                         |
#| codePackage     | String | The code package S3 object key name. Typically, filename.zip                                              |
#| slackWebhookURL | String | Slack channel webhook URL. If you don't have one already, check https://api.slack.com/messaging/webhooks. |

Parameters:
  s3Bucket:
    Type: String
    Description: S3 Bucket where your Lambda functions and StepFunctions state machines    are stored.
  codePackage:
    Type: String
    Description: S3 key for the Lambda Code. 
  defaultSlackWebhookURL:
    Type: String
    Description: Default Slack Webhook URL.
  defaultTeamsWebhookURL:
    Type: String
    Description: Default Teams Webhook URL.
  FeatureFlagDisplayAccountName:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: Select whether to display Account Name in the Notification or not. This will require special permissions for the Lambda function to access the Organisations API.

Conditions:
  displayAccountNameEnabled: !Equals 
    - !Ref FeatureFlagDisplayAccountName
    - true

Outputs:
  snsTopicArn:
    Description: The Arn of the SNS topic created by the stack. This topic Arn is to be configured in the Anomaly Detection Subscription Configuratios.  
    Value: !Ref SnsTopicCostAnomaly

Mappings: 
  AppConfigLayerArn: 
    us-east-1:
      AppConfigLayerArn: arn:aws:lambda:us-east-1:027255383542:layer:AWS-AppConfig-Extension:44
    us-east-2: 
      AppConfigLayerArn: arn:aws:lambda:us-east-2:728743619870:layer:AWS-AppConfig-Extension:42
    us-west-1: 
      AppConfigLayerArn: arn:aws:lambda:us-west-1:958113053741:layer:AWS-AppConfig-Extension:37
    us-west-2: 
      AppConfigLayerArn: arn:aws:lambda:us-west-2:359756378197:layer:AWS-AppConfig-Extension:62
    ap-southeast-2: 
      AppConfigLayerArn: arn:aws:lambda:ap-southeast-2:080788657173:layer:AWS-AppConfig-Extension:49
    ca-central-1: 
      AppConfigLayerArn: arn:aws:lambda:ca-central-1:039592058896:layer:AWS-AppConfig-Extension:42
    eu-central-1: 
      AppConfigLayerArn: arn:aws:lambda:eu-central-1:066940009817:layer:AWS-AppConfig-Extension:49
    eu-west-1: 
      AppConfigLayerArn: arn:aws:lambda:eu-west-1:434848589818:layer:AWS-AppConfig-Extension:41
    eu-west-2: 
      AppConfigLayerArn: arn:aws:lambda:eu-west-2:282860088358:layer:AWS-AppConfig-Extension:42
    eu-west-3: 
      AppConfigLayerArn: arn:aws:lambda:eu-west-3:493207061005:layer:AWS-AppConfig-Extension:43
    eu-north-1: 
      AppConfigLayerArn: arn:aws:lambda:eu-north-1:646970417810:layer:AWS-AppConfig-Extension:61
    eu-south-1: 
      AppConfigLayerArn: arn:aws:lambda:eu-south-1:203683718741:layer:AWS-AppConfig-Extension:39
    cn-north-1: 
      AppConfigLayerArn: arn:aws-cn:lambda:cn-north-1:615057806174:layer:AWS-AppConfig-Extension:38
    cn-northwest-1: 
      AppConfigLayerArn: arn:aws-cn:lambda:cn-northwest-1:615084187847:layer:AWS-AppConfig-Extension:38
    ap-east-1: 
      AppConfigLayerArn: arn:aws:lambda:ap-east-1:630222743974:layer:AWS-AppConfig-Extension:39
    ap-northeast-1: 
      AppConfigLayerArn: arn:aws:lambda:ap-northeast-1:980059726660:layer:AWS-AppConfig-Extension:38
    ap-northeast-3: 
      AppConfigLayerArn: arn:aws:lambda:ap-northeast-3:706869817123:layer:AWS-AppConfig-Extension:24
    ap-northeast-2: 
      AppConfigLayerArn: arn:aws:lambda:ap-northeast-2:826293736237:layer:AWS-AppConfig-Extension:49
    ap-southeast-1: 
      AppConfigLayerArn: arn:aws:lambda:ap-southeast-1:421114256042:layer:AWS-AppConfig-Extension:38
    ap-south-1: 
      AppConfigLayerArn: arn:aws:lambda:ap-south-1:554480029851:layer:AWS-AppConfig-Extension:50
    sa-east-1: 
      AppConfigLayerArn: arn:aws:lambda:sa-east-1:000010852771:layer:AWS-AppConfig-Extension:44
    af-south-1: 
      AppConfigLayerArn: arn:aws:lambda:af-south-1:574348263942:layer:AWS-AppConfig-Extension:39
    me-south-1: 
      AppConfigLayerArn: arn:aws:lambda:me-south-1:559955524753:layer:AWS-AppConfig-Extension:39
    us-gov-east-1:
      AppConfigLayerArn: arn:aws-us-gov:lambda:us-gov-east-1:946561847325:layer:AWS-AppConfig-Extension:15
    us-gov-west-1:
      AppConfigLayerArn: arn:aws-us-gov:lambda:us-gov-west-1:946746059096:layer:AWS-AppConfig-Extension:15
    

    
     
